/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomElement {
        "details": string;
        "title": string;
    }
}
declare global {
    interface HTMLCustomElementElement extends Components.CustomElement, HTMLStencilElement {
    }
    var HTMLCustomElementElement: {
        prototype: HTMLCustomElementElement;
        new (): HTMLCustomElementElement;
    };
    interface HTMLElementTagNameMap {
        "custom-element": HTMLCustomElementElement;
    }
}
declare namespace LocalJSX {
    interface CustomElement {
        "details"?: string;
        "onButtonPressed"?: (event: CustomEvent<any>) => void;
        "title"?: string;
    }
    interface IntrinsicElements {
        "custom-element": CustomElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-element": LocalJSX.CustomElement & JSXBase.HTMLAttributes<HTMLCustomElementElement>;
        }
    }
}
